import type { Language } from './shared/api';

export const copy = {
  product: { en: 'Horizon', es: 'Horizon' },
  skip: { en: 'Skip to start page', es: 'Ir a la página de inicio' },
  tabs: { en: 'Tabs', es: 'Pestañas' },
  home: { en: 'Home', es: 'Inicio' },
  bread: { en: 'Sourdough bread: the complete guide', es: 'Pan de masa madre: la guía completa' },
  routes: { en: 'Routes through Patagonia in autumn', es: 'Rutas por la Patagonia en otoño' },
  breadInitial: { en: 'S', es: 'P' },
  routesInitial: { en: 'R', es: 'R' },
  personal: { en: 'Personal', es: 'Personal' },
  work: { en: 'Work', es: 'Trabajo' },
  profile: { en: 'Profile: {name}', es: 'Perfil: {name}' },
  newTab: { en: 'New tab', es: 'Nueva pestaña' },
  closeTab: { en: 'Close tab', es: 'Cerrar pestaña' },
  toolbar: { en: 'Toolbar', es: 'Barra de herramientas' },
  back: { en: 'Back', es: 'Atrás' },
  forward: { en: 'Forward', es: 'Adelante' },
  reload: { en: 'Reload', es: 'Recargar' },
  address: { en: 'Search or enter an address', es: 'Buscá o escribí una dirección' },
  protection: { en: 'Site protection', es: 'Protección del sitio' },
  blockingOnSite: { en: 'Blocking on this site', es: 'Bloqueo en este sitio' },
  blockingOffSite: { en: 'Blocking off on this site', es: 'Bloqueo desactivado en este sitio' },
  blockingNotReady: { en: 'Ad and tracker blocking is not ready yet', es: 'El bloqueo de anuncios y rastreadores todavía no está listo' },
  blockAdsTrackers: { en: 'Block ads and trackers', es: 'Bloquear anuncios y rastreadores' },
  nothingBlocked: { en: 'Nothing blocked yet', es: 'Todavía no se bloqueó nada' },
  blockedOne: { en: '{count} blocked', es: '{count} bloqueado' },
  blockedMany: { en: '{count} blocked', es: '{count} bloqueados' },
  blockedBreakdown: { en: '{total}: {categories}', es: '{total}: {categories}' },
  blockedAd: { en: '{count} ad', es: '{count} anuncio' },
  blockedAds: { en: '{count} ads', es: '{count} anuncios' },
  blockedTracker: { en: '{count} tracker', es: '{count} rastreador' },
  blockedTrackers: { en: '{count} trackers', es: '{count} rastreadores' },
  blockedCookie: { en: '{count} cookie', es: '{count} cookie' },
  blockedCookies: { en: '{count} cookies', es: '{count} cookies' },
  blockingEnabled: { en: 'Blocking enabled on {host}', es: 'Bloqueo activado en {host}' },
  blockingDisabled: { en: 'Blocking off on {host}', es: 'Bloqueo desactivado en {host}' },
  darkModeOnSite: { en: 'Dark mode on this site', es: 'Modo oscuro en este sitio' },
  darkPagesOff: { en: 'Dark pages are off. Turn them on in the menu.', es: 'Las páginas oscuras están apagadas. Activalas en el menú.' },
  darkPagesSystemLight: { en: 'Dark pages follow the system, which is light now.', es: 'Las páginas oscuras siguen al sistema, que ahora está en claro.' },
  darkModeEnabled: { en: 'Dark mode on for {host}', es: 'Modo oscuro activado en {host}' },
  darkModeDisabled: { en: 'Dark mode off for {host}', es: 'Modo oscuro desactivado en {host}' },
  sitePermissions: { en: 'Permissions', es: 'Permisos' },
  permissionCamera: { en: 'Camera', es: 'Cámara' },
  permissionMicrophone: { en: 'Microphone', es: 'Micrófono' },
  permissionLocation: { en: 'Location', es: 'Ubicación' },
  permissionNotifications: { en: 'Notifications', es: 'Notificaciones' },
  permissionAsk: { en: 'Ask', es: 'Preguntar' },
  permissionAllowed: { en: 'Allowed', es: 'Permitido' },
  permissionBlocked: { en: 'Blocked', es: 'Bloqueado' },
  permissionAllow: { en: 'Allow', es: 'Permitir' },
  permissionBlock: { en: 'Block', es: 'Bloquear' },
  siteWantsTo: { en: '{host} wants to', es: '{host} quiere' },
  useCamera: { en: 'Use your camera', es: 'Usar tu cámara' },
  useMicrophone: { en: 'Use your microphone', es: 'Usar tu micrófono' },
  knowLocation: { en: 'Know your location', es: 'Conocer tu ubicación' },
  showNotifications: { en: 'Show notifications', es: 'Mostrar notificaciones' },
  bookmark: { en: 'Bookmark', es: 'Guardar favorito' },
  notebooks: { en: 'Notebooks', es: 'Cuadernos' },
  notebookHint: { en: 'Notebook', es: 'Cuaderno' },
  capturePurpose: { en: 'Capture this page', es: 'Capturar esta página' },
  captureKind: { en: 'Capture type', es: 'Tipo de captura' },
  captureText: { en: 'Text', es: 'Texto' },
  captureArea: { en: 'Area', es: 'Área' },
  capturePage: { en: 'Full page', es: 'Página completa' },
  saveToNotebook: { en: 'Save to notebook', es: 'Guardar en un cuaderno' },
  chooseNotebook: { en: 'Choose a notebook', es: 'Elegir un cuaderno' },
  newNotebook: { en: 'New notebook', es: 'Nuevo cuaderno' },
  notebookName: { en: 'Notebook name', es: 'Nombre del cuaderno' },
  notebookActions: { en: 'Notebook actions', es: 'Acciones del cuaderno' },
  renameNotebook: { en: 'Rename notebook', es: 'Renombrar cuaderno' },
  deleteNotebook: { en: 'Delete notebook', es: 'Eliminar cuaderno' },
  deleteItem: { en: 'Delete {title}', es: 'Eliminar {title}' },
  notebookDeleted: { en: 'Notebook deleted', es: 'Cuaderno eliminado' },
  notebookItemDeleted: { en: 'Item deleted', es: 'Elemento eliminado' },
  notebookSaved: { en: 'Saved to {name}', es: 'Se guardó en {name}' },
  openNotebook: { en: 'Open', es: 'Abrir' },
  newNote: { en: 'New note', es: 'Nueva nota' },
  noteTitle: { en: 'Title', es: 'Título' },
  noteText: { en: 'Text', es: 'Texto' },
  captureNote: { en: 'Note', es: 'Nota' },
  captureNotePlaceholder: { en: 'Add a note…', es: 'Agregá una nota…' },
  noteOne: { en: '1 note', es: '1 nota' },
  noteMany: { en: '{count} notes', es: '{count} notas' },
  captureOne: { en: '1 capture', es: '1 captura' },
  captureMany: { en: '{count} captures', es: '{count} capturas' },
  notebookCounts: { en: '{notes} and {captures}', es: '{notes} y {captures}' },
  resumeNotebook: { en: 'Continue with {name}', es: 'Seguir con {name}' },
  emptyNotebooksTitle: { en: 'Keep your research in notebooks', es: 'Guardá tu investigación en cuadernos' },
  emptyNotebooks: { en: 'Keep notes, selected text and page captures together. They stay on this computer.', es: 'Reuní notas, texto seleccionado y capturas de páginas. Quedan en esta computadora.' },
  emptyNotebook: { en: 'Add a note, or capture a page with the Notebooks button.', es: 'Agregá una nota o capturá una página con el botón Cuadernos.' },
  notebookReadFailed: { en: 'The notebook file could not be read. It was set aside; page captures were kept.', es: 'No se pudo leer el archivo de cuadernos. Se apartó el archivo y se conservaron las capturas.' },
  NOTEBOOK_LOCKED: { en: 'Notebooks cannot be opened because system encryption is unavailable. Nothing was lost. They will open again once it is available.', es: 'No se pueden abrir los cuadernos porque el cifrado del sistema no está disponible. No se perdió nada. Se podrán abrir cuando vuelva a estar disponible.' },
  filterNotebooks: { en: 'Filter notebooks', es: 'Filtrar cuadernos' },
  noNotebookResults: { en: 'No notebooks match.', es: 'No hay cuadernos que coincidan.' },
  newNotebookNamed: { en: 'New notebook: {name}', es: 'Nuevo cuaderno: {name}' },
  capturingPage: { en: 'Capturing the page', es: 'Capturando la página' },
  notebookImageFailed: { en: 'This capture image could not be read.', es: 'No se pudo leer la imagen de esta captura.' },
  notebookImage: { en: 'Captured image: {title}', es: 'Imagen capturada: {title}' },
  captureCut: { en: 'This capture stops at the maximum page height.', es: 'La captura termina en la altura máxima de página.' },
  captureInstructions: { en: 'Drag, or click each corner. Arrow keys move the area by 10 pixels; Shift with arrow keys resizes it by 10 pixels. Hold Alt with either to adjust by 1 pixel.', es: 'Arrastrá o hacé clic en cada esquina. Las flechas mueven el área de a 10 píxeles; Mayús con las flechas cambia su tamaño de a 10 píxeles. Mantené Alt con cualquiera de las dos opciones para ajustar de a 1 píxel.' },
  captureSize: { en: 'Area: {width} by {height} pixels', es: 'Área: {width} por {height} píxeles' },
  captureSource: { en: 'From {site}, {date}', es: 'De {site}, {date}' },
  captureTextHint: { en: 'Saves the text selected on the page before capture mode opened.', es: 'Guarda el texto seleccionado en la página antes de abrir la captura.' },
  NOTEBOOK_NAME_INVALID: { en: 'Use a name without control characters.', es: 'Usá un nombre sin caracteres de control.' },
  NOTEBOOK_NAME_EMPTY: { en: 'Enter a notebook name.', es: 'Escribí un nombre para el cuaderno.' },
  NOTEBOOK_NAME_LONG: { en: 'Use 80 characters or fewer.', es: 'Usá hasta 80 caracteres.' },
  NOTEBOOK_NAME_DUPLICATE: { en: 'A notebook already uses this name.', es: 'Ya hay un cuaderno con este nombre.' },
  NOTEBOOK_LIMIT: { en: 'You can have up to 200 notebooks.', es: 'Podés tener hasta 200 cuadernos.' },
  NOTEBOOK_ITEM_LIMIT: { en: 'This notebook has reached its limit of 2,000 items.', es: 'Este cuaderno llegó al límite de 2.000 elementos.' },
  NOTEBOOK_NOT_FOUND: { en: 'This notebook is no longer available.', es: 'Este cuaderno ya no está disponible.' },
  NOTEBOOK_ITEM_NOT_FOUND: { en: 'This item is no longer in the notebook.', es: 'Este elemento ya no está en el cuaderno.' },
  NOTEBOOK_ITEM_INVALID: { en: 'This item could not be saved. Check its text and try again.', es: 'No se pudo guardar este elemento. Revisá el texto y probá de nuevo.' },
  NOTEBOOK_STORAGE_FAILED: { en: 'The notebook could not be saved. Check disk access and try again.', es: 'No se pudo guardar el cuaderno. Revisá el acceso al disco y probá de nuevo.' },
  NOTEBOOK_STORAGE_FULL: { en: 'Capture storage is full. Remove an unneeded capture and try again.', es: 'El espacio para capturas está lleno. Eliminá una captura que no necesites y probá de nuevo.' },
  CAPTURE_TOO_LARGE: { en: 'This capture is too large. Choose a smaller area.', es: 'Esta captura es demasiado grande. Elegí un área más chica.' },
  CAPTURE_UNAVAILABLE: { en: 'This page cannot be captured. Open a web page and try again.', es: 'Esta página no se puede capturar. Abrí una página web y probá de nuevo.' },
  CAPTURE_CHANGED: { en: 'The page changed during capture. Capture it again.', es: 'La página cambió durante la captura. Volvé a capturarla.' },
  CAPTURE_AREA_SMALL: { en: 'Choose an area at least 8 by 8 pixels.', es: 'Elegí un área de al menos 8 por 8 píxeles.' },
  CAPTURE_PAGE_HIDDEN: { en: 'The full page needs to be visible. Close any open panel and try again.', es: 'La página completa tiene que estar visible. Cerrá los paneles abiertos y probá de nuevo.' },
  CAPTURE_TIMEOUT: { en: 'The page took too long to capture. Try again.', es: 'La página tardó demasiado en capturarse. Probá de nuevo.' },
  CAPTURE_FAILED: { en: 'The page capture failed. Try again.', es: 'Falló la captura de la página. Probá de nuevo.' },
  NOTHING_SELECTED: { en: 'No text was selected. Cancel, select text on the page, then capture it.', es: 'No había texto seleccionado. Cancelá, seleccioná texto en la página y volvé a capturarlo.' },
  lyra: { en: 'Lyra', es: 'Lyra' },
  menu: { en: 'Menu', es: 'Menú' },
  pageMenu: { en: 'Page menu', es: 'Menú de la página' },
  openLink: { en: 'Open link in new tab', es: 'Abrir enlace en una nueva pestaña' },
  copyLink: { en: 'Copy link address', es: 'Copiar dirección del enlace' },
  openImage: { en: 'Open image in new tab', es: 'Abrir imagen en una nueva pestaña' },
  saveImage: { en: 'Save image', es: 'Guardar imagen' },
  copyImage: { en: 'Copy image', es: 'Copiar imagen' },
  copyImageAddress: { en: 'Copy image address', es: 'Copiar dirección de la imagen' },
  copy: { en: 'Copy', es: 'Copiar' },
  redo: { en: 'Redo', es: 'Rehacer' },
  cut: { en: 'Cut', es: 'Cortar' },
  paste: { en: 'Paste', es: 'Pegar' },
  selectAll: { en: 'Select all', es: 'Seleccionar todo' },
  minimize: { en: 'Minimize', es: 'Minimizar' },
  maximize: { en: 'Maximize or restore', es: 'Maximizar o restaurar' },
  closeWindow: { en: 'Close window', es: 'Cerrar ventana' },
  search: { en: 'Search the web or enter an address', es: 'Buscá en la web o escribí una dirección' },
  shortcuts: { en: 'Shortcuts', es: 'Atajos' },
  wikipedia: { en: 'Wikipedia', es: 'Wikipedia' },
  youtube: { en: 'YouTube', es: 'YouTube' },
  maps: { en: 'Maps', es: 'Mapas' },
  news: { en: 'News', es: 'Noticias' },
  mail: { en: 'Mail', es: 'Correo' },
  notebookTitle: { en: 'Trip to Patagonia', es: 'Viaje a la Patagonia' },
  resumeMeta: { en: '6 notes, yesterday', es: '6 notas, ayer' },
  noteRoute: { en: 'Route 40: gravel sections and fuel stops', es: 'Ruta 40: tramos de ripio y dónde cargar nafta' },
  noteTrails: { en: 'El Chaltén in April: open trails', es: 'El Chaltén en abril: senderos abiertos' },
  noteBudget: { en: 'Budget: accommodation and car', es: 'Presupuesto: alojamiento y auto' },
  sourceRoute: { en: 'rutasdelsur.example', es: 'rutasdelsur.example' },
  sourceCapture: { en: 'screenshot', es: 'captura de pantalla' },
  sourceFullPage: { en: 'full page', es: 'página completa' },
  sourceNote: { en: 'personal note', es: 'nota propia' },
  askLyra: { en: 'Ask Lyra about what you have open', es: 'Preguntale a Lyra por lo que tenés abierto' },
  unavailable: { en: 'Lyra is a preview. It is not available yet.', es: 'Lyra es una vista previa. Todavía no está disponible.' },
  startupError: { en: 'Horizon could not start. Close the window and try again.', es: 'Horizon no pudo iniciar. Cerrá la ventana y probá de nuevo.' },
  actionError: { en: 'The window action failed. Try again.', es: 'La acción de la ventana falló. Probá de nuevo.' },
  browserError: { en: 'The action could not be completed. Try again.', es: 'No se pudo completar la acción. Probá de nuevo.' },
  storageReadError: { en: 'Saved data for this profile could not be read. A copy was kept.', es: 'No se pudieron leer los datos guardados de este perfil. Se conservó una copia.' },
  storageError: { en: 'Local data could not be saved. Check available disk space and try again.', es: 'No se pudieron guardar los datos locales. Revisá el espacio disponible y probá de nuevo.' },
  stop: { en: 'Stop loading', es: 'Detener carga' },
  loading: { en: 'Loading…', es: 'Cargando…' },
  history: { en: 'History', es: 'Historial' },
  bookmarks: { en: 'Bookmarks', es: 'Favoritos' },
  downloads: { en: 'Downloads', es: 'Descargas' },
  find: { en: 'Find in page', es: 'Buscar en la página' },
  previousMatch: { en: 'Previous match', es: 'Coincidencia anterior' },
  nextMatch: { en: 'Next match', es: 'Coincidencia siguiente' },
  matchOf: { en: 'of', es: 'de' },
  notFound: { en: 'No matches found', es: 'No se encontraron coincidencias' },
  suggestions: { en: 'History, bookmark and notebook suggestions', es: 'Sugerencias del historial, favoritos y cuadernos' },
  searchWeb: { en: 'Search the web for “{query}”', es: 'Buscar «{query}» en la web' },
  close: { en: 'Close', es: 'Cerrar' },
  delete: { en: 'Delete', es: 'Eliminar' },
  clearHistory: { en: 'Clear all history', es: 'Borrar todo el historial' },
  confirmClearHistory: { en: 'Clear all history?', es: '¿Borrar todo el historial?' },
  clear: { en: 'Clear', es: 'Borrar' },
  undo: { en: 'Undo', es: 'Deshacer' },
  entryDeleted: { en: 'Entry deleted', es: 'Entrada eliminada' },
  historyCleared: { en: 'History cleared', es: 'Historial borrado' },
  bookmarkDeleted: { en: 'Bookmark deleted', es: 'Favorito eliminado' },
  downloadRemoved: { en: 'Removed from the list', es: 'Se quitó de la lista' },
  pageLoading: { en: 'Loading {page}', es: 'Cargando {page}' },
  pageLoaded: { en: '{page} loaded', es: '{page} se cargó' },
  bookmarkAdded: { en: 'Added to bookmarks', es: 'Se agregó a favoritos' },
  bookmarkRemoved: { en: 'Removed from bookmarks', es: 'Se quitó de favoritos' },
  bookmarkRenamed: { en: 'Bookmark renamed', es: 'Favorito renombrado' },
  filterHistory: { en: 'Search history', es: 'Buscar en el historial' },
  filterBookmarks: { en: 'Search bookmarks', es: 'Buscar en favoritos' },
  emptyHistoryTitle: { en: 'No history yet', es: 'Todavía no hay historial' },
  emptyHistory: { en: 'Pages you visit appear here, newest first.', es: 'Las páginas que visitás aparecen acá, de la más reciente a la más vieja.' },
  emptyBookmarksTitle: { en: 'No bookmarks yet', es: 'Todavía no hay favoritos' },
  emptyBookmarks: { en: 'Use the star in the address bar to save a page.', es: 'Usá la estrella de la barra de direcciones para guardar una página.' },
  emptyDownloadsTitle: { en: 'No downloads yet', es: 'Todavía no hay descargas' },
  emptyDownloads: { en: 'Files you download are saved in your Downloads folder.', es: 'Los archivos que descargás se guardan en tu carpeta Descargas.' },
  noResultsTitle: { en: 'No matches', es: 'Sin coincidencias' },
  noResults: { en: 'No entries match this search. Clear it to see the full list.', es: 'No hay entradas que coincidan con esta búsqueda. Borrala para ver toda la lista.' },
  browseWeb: { en: 'Browse the web', es: 'Navegar por la web' },
  openDownloadsFolder: { en: 'Open Downloads folder', es: 'Abrir carpeta Descargas' },
  clearFilter: { en: 'Clear search', es: 'Borrar búsqueda' },
  rename: { en: 'Rename', es: 'Renombrar' },
  bookmarkName: { en: 'Bookmark name', es: 'Nombre del favorito' },
  save: { en: 'Save', es: 'Guardar' },
  cancel: { en: 'Cancel', es: 'Cancelar' },
  showFolder: { en: 'Show in folder', es: 'Mostrar en la carpeta' },
  removeDownload: { en: 'Remove from list', es: 'Quitar de la lista' },
  progressing: { en: 'Downloading', es: 'Descargando' },
  completed: { en: 'Completed', es: 'Completada' },
  failed: { en: 'Failed', es: 'Fallida' },
  cancelled: { en: 'Cancelled', es: 'Cancelada' },
  loadError: { en: 'This page could not be loaded', es: 'No se pudo cargar esta página' },
  siteNotFound: { en: 'Site not found', es: 'No se encontró el sitio' },
  checkAddress: { en: 'Check that the address is spelled correctly.', es: 'Revisá que la dirección esté bien escrita.' },
  offline: { en: 'You are offline', es: 'No tenés conexión' },
  checkConnection: { en: 'Check your internet connection.', es: 'Revisá tu conexión a internet.' },
  notResponding: { en: 'This site is not responding', es: 'Este sitio no responde' },
  tryLater: { en: 'Try again in a few minutes.', es: 'Probá de nuevo en unos minutos.' },
  insecureConnection: { en: 'This connection is not secure', es: 'Esta conexión no es segura' },
  connectionUnsafe: { en: 'Horizon could not establish a secure connection to this site.', es: 'Horizon no pudo establecer una conexión segura con este sitio.' },
  blockedAddress: { en: 'This address is blocked', es: 'Esta dirección está bloqueada' },
  addressBlocked: { en: 'Horizon cannot open this address.', es: 'Horizon no puede abrir esta dirección.' },
  pageCrashed: { en: 'This page crashed', es: 'Esta página dejó de funcionar' },
  reloadPage: { en: 'Reload the page to continue.', es: 'Recargá la página para seguir.' },
  tryLoadingAgain: { en: 'Try loading the page again.', es: 'Probá cargar la página de nuevo.' },
  retry: { en: 'Try again', es: 'Volver a intentar' },
  removeBookmark: { en: 'Remove bookmark', es: 'Quitar favorito' },
  zoomReset: { en: 'Reset page zoom', es: 'Restablecer zoom de la página' },
  highContrast: { en: 'High contrast', es: 'Alto contraste' },
  theme: { en: 'Theme', es: 'Tema' },
  darkPages: { en: 'Dark pages', es: 'Páginas oscuras' },
  off: { en: 'Off', es: 'No' },
  on: { en: 'On', es: 'Sí' },
  darkStrength: { en: 'Strength', es: 'Intensidad' },
  soft: { en: 'Soft', es: 'Suave' },
  standard: { en: 'Standard', es: 'Normal' },
  deep: { en: 'Deep', es: 'Fuerte' },
  darkTone: { en: 'Tone', es: 'Tono' },
  neutral: { en: 'Neutral', es: 'Neutro' },
  warm: { en: 'Warm', es: 'Cálido' },
  system: { en: 'System', es: 'Sistema' },
  amber: { en: 'Amber', es: 'Amber' },
  daylight: { en: 'Daylight', es: 'Daylight' },
  profiles: { en: "Profiles", es: "Perfiles" },
  newProfile: { en: "New profile", es: "Nuevo perfil" },
  manageProfiles: { en: "Manage profiles", es: "Administrar perfiles" },
  profileName: { en: "Name", es: "Nombre" },
  profileNamePlaceholder: { en: "Profile name", es: "Nombre del perfil" },
  profileColour: { en: "Colour", es: "Color" },
  create: { en: "Create", es: "Crear" },
  editProfile: { en: "Edit", es: "Editar" },
  switchProfile: { en: "Switch", es: "Cambiar" },
  currentProfile: { en: "Current profile", es: "Perfil actual" },
  deleteProfileLabel: { en: "Delete {name}", es: "Eliminar {name}" },
  deleteProfile: { en: "Delete profile", es: "Eliminar perfil" },
  confirmDeleteProfile: { en: "Delete {name}? Its tabs, history, bookmarks and sign-ins are erased from this computer.", es: "¿Eliminar {name}? Sus pestañas, historial, favoritos e inicios de sesión se borran de esta computadora." },
  lastProfile: { en: "One profile always remains", es: "Siempre queda un perfil" },
  switchedProfile: { en: "Switched to {name}", es: "Se cambió a {name}" },
  createdProfile: { en: "Created {name}", es: "Se creó {name}" },
  updatedProfile: { en: "Saved {name}", es: "Se guardó {name}" },
  deletedProfile: { en: "{name} deleted", es: "{name} eliminado" },
  profileTabs: { en: "{count} tabs", es: "{count} pestañas" },
  profileTab: { en: "1 tab", es: "1 pestaña" },
  profileNoTabs: { en: "No open tabs", es: "Sin pestañas abiertas" },
  profileNameEmpty: { en: "Enter a name.", es: "Escribí un nombre." },
  profileNameLong: { en: "Use 40 characters or fewer.", es: "Usá hasta 40 caracteres." },
  profileNameInvalid: { en: "Use a name without control characters.", es: "Usá un nombre sin caracteres de control." },
  profileNameDuplicate: { en: "A profile already uses this name.", es: "Ya hay un perfil con este nombre." },
  profileLimit: { en: "You can have up to 20 profiles.", es: "Podés tener hasta 20 perfiles." },
  colourAmber: { en: "Amber", es: "Ámbar" },
  colourBlue: { en: "Blue", es: "Azul" },
  colourGreen: { en: "Green", es: "Verde" },
  colourRed: { en: "Red", es: "Rojo" },
  colourYellow: { en: "Yellow", es: "Amarillo" },
  colourGrey: { en: "Grey", es: "Gris" },
  colourPurple: { en: "Purple", es: "Violeta" },
  colourCyan: { en: "Cyan", es: "Cian" },
} as const;

export type CopyKey = keyof typeof copy;
export const text = (key: CopyKey, language: Language): string => copy[key][language];
