import type { Language } from './shared/api';

export const copy = {
  product: { en: 'Horizon', es: 'Horizon' },
  skip: { en: 'Skip to start page', es: 'Ir a la página de inicio' },
  tabs: { en: 'Tabs', es: 'Pestañas' },
  home: { en: 'Home', es: 'Inicio' },
  bread: { en: 'Sourdough bread: the complete guide', es: 'Pan de masa madre: la guía completa' },
  routes: { en: 'Routes through Patagonia in autumn', es: 'Rutas por la Patagonia en otoño' },
  breadInitial: { en: 'S', es: 'P' },
  routesInitial: { en: 'R', es: 'R' },
  personal: { en: 'Personal', es: 'Personal' },
  profile: { en: 'Profile: Personal', es: 'Perfil: Personal' },
  newTab: { en: 'New tab', es: 'Nueva pestaña' },
  closeTab: { en: 'Close tab', es: 'Cerrar pestaña' },
  toolbar: { en: 'Toolbar', es: 'Barra de herramientas' },
  back: { en: 'Back', es: 'Atrás' },
  forward: { en: 'Forward', es: 'Adelante' },
  reload: { en: 'Reload', es: 'Recargar' },
  address: { en: 'Search or enter an address', es: 'Buscá o escribí una dirección' },
  protection: { en: 'Site protection', es: 'Protección del sitio' },
  bookmark: { en: 'Bookmark', es: 'Guardar favorito' },
  notebooks: { en: 'Notebooks', es: 'Notebooks' },
  lyra: { en: 'Lyra', es: 'Lyra' },
  menu: { en: 'Menu', es: 'Menú' },
  minimize: { en: 'Minimize', es: 'Minimizar' },
  maximize: { en: 'Maximize or restore', es: 'Maximizar o restaurar' },
  closeWindow: { en: 'Close window', es: 'Cerrar ventana' },
  search: { en: 'Search the web or enter an address', es: 'Buscá en la web o escribí una dirección' },
  shortcuts: { en: 'Shortcuts', es: 'Atajos' },
  wikipedia: { en: 'Wikipedia', es: 'Wikipedia' },
  youtube: { en: 'YouTube', es: 'YouTube' },
  maps: { en: 'Maps', es: 'Mapas' },
  news: { en: 'News', es: 'Noticias' },
  mail: { en: 'Mail', es: 'Correo' },
  resume: { en: 'Continue with Trip to Patagonia', es: 'Seguir con Viaje a la Patagonia' },
  resumeMeta: { en: '6 notes and 3 captures, last night', es: '6 notas y 3 capturas, ayer a la noche' },
  openNotebook: { en: 'Open notebook', es: 'Abrir notebook' },
  noteRoute: { en: 'Route 40: gravel sections and fuel stops', es: 'Ruta 40: tramos de ripio y dónde cargar nafta' },
  noteTrails: { en: 'El Chaltén in April: open trails', es: 'El Chaltén en abril: senderos abiertos' },
  noteBudget: { en: 'Budget: accommodation and car', es: 'Presupuesto: alojamiento y auto' },
  sourceRoute: { en: 'rutasdelsur.example', es: 'rutasdelsur.example' },
  sourceCapture: { en: 'screenshot', es: 'captura de pantalla' },
  sourceNote: { en: 'personal note', es: 'nota propia' },
  askLyra: { en: 'Ask Lyra about what you have open', es: 'Preguntale a Lyra por lo que tenés abierto' },
  unavailable: { en: 'Notebooks and Lyra are previews. These features are not available yet.', es: 'Notebooks y Lyra son vistas previas. Estas funciones todavía no están disponibles.' },
  startupError: { en: 'Horizon could not start. Close the window and try again.', es: 'Horizon no pudo iniciar. Cerrá la ventana y probá de nuevo.' },
  actionError: { en: 'The window action failed. Try again.', es: 'La acción de la ventana falló. Probá de nuevo.' },
  browserError: { en: 'The action could not be completed. Try again.', es: 'No se pudo completar la acción. Probá de nuevo.' },
  storageError: { en: 'Local data could not be saved. Check available disk space and try again.', es: 'No se pudieron guardar los datos locales. Revisá el espacio disponible y probá de nuevo.' },
  stop: { en: 'Stop loading', es: 'Detener carga' },
  loading: { en: 'Loading…', es: 'Cargando…' },
  history: { en: 'History', es: 'Historial' },
  bookmarks: { en: 'Bookmarks', es: 'Favoritos' },
  downloads: { en: 'Downloads', es: 'Descargas' },
  find: { en: 'Find in page', es: 'Buscar en la página' },
  previousMatch: { en: 'Previous match', es: 'Coincidencia anterior' },
  nextMatch: { en: 'Next match', es: 'Coincidencia siguiente' },
  matchOf: { en: 'of', es: 'de' },
  notFound: { en: 'No matches found', es: 'No se encontraron coincidencias' },
  suggestions: { en: 'History and bookmark suggestions', es: 'Sugerencias del historial y favoritos' },
  noSuggestions: { en: 'No local suggestions. Press Enter to search with DuckDuckGo.', es: 'No hay sugerencias locales. Presioná Enter para buscar con DuckDuckGo.' },
  close: { en: 'Close', es: 'Cerrar' },
  delete: { en: 'Delete', es: 'Eliminar' },
  clearHistory: { en: 'Clear all history', es: 'Borrar todo el historial' },
  confirmClearHistory: { en: 'Clear all history?', es: '¿Borrar todo el historial?' },
  clear: { en: 'Clear', es: 'Borrar' },
  undo: { en: 'Undo', es: 'Deshacer' },
  entryDeleted: { en: 'Entry deleted', es: 'Entrada eliminada' },
  historyCleared: { en: 'History cleared', es: 'Historial borrado' },
  bookmarkDeleted: { en: 'Bookmark deleted', es: 'Favorito eliminado' },
  downloadRemoved: { en: 'Removed from the list', es: 'Se quitó de la lista' },
  pageLoading: { en: 'Loading {page}', es: 'Cargando {page}' },
  pageLoaded: { en: '{page} loaded', es: '{page} se cargó' },
  bookmarkAdded: { en: 'Added to bookmarks', es: 'Se agregó a favoritos' },
  bookmarkRemoved: { en: 'Removed from bookmarks', es: 'Se quitó de favoritos' },
  filterHistory: { en: 'Search history', es: 'Buscar en el historial' },
  filterBookmarks: { en: 'Search bookmarks', es: 'Buscar en favoritos' },
  emptyHistory: { en: 'No browsing history yet.', es: 'Todavía no hay historial de navegación.' },
  emptyBookmarks: { en: 'No bookmarks yet. Use the star to save a page.', es: 'Todavía no hay favoritos. Usá la estrella para guardar una página.' },
  emptyDownloads: { en: 'No downloads yet.', es: 'Todavía no hay descargas.' },
  noResults: { en: 'No results for this search.', es: 'No hay resultados para esta búsqueda.' },
  rename: { en: 'Rename', es: 'Renombrar' },
  bookmarkName: { en: 'Bookmark name', es: 'Nombre del favorito' },
  save: { en: 'Save', es: 'Guardar' },
  cancel: { en: 'Cancel', es: 'Cancelar' },
  showFolder: { en: 'Show in folder', es: 'Mostrar en la carpeta' },
  removeDownload: { en: 'Remove from list', es: 'Quitar de la lista' },
  progressing: { en: 'Downloading', es: 'Descargando' },
  completed: { en: 'Completed', es: 'Completada' },
  failed: { en: 'Failed', es: 'Fallida' },
  cancelled: { en: 'Cancelled', es: 'Cancelada' },
  loadError: { en: 'This page could not be loaded', es: 'No se pudo cargar esta página' },
  siteNotFound: { en: 'Site not found', es: 'No se encontró el sitio' },
  checkAddress: { en: 'Check that the address is spelled correctly.', es: 'Revisá que la dirección esté bien escrita.' },
  offline: { en: 'You are offline', es: 'No tenés conexión' },
  checkConnection: { en: 'Check your internet connection.', es: 'Revisá tu conexión a internet.' },
  notResponding: { en: 'This site is not responding', es: 'Este sitio no responde' },
  tryLater: { en: 'Try again in a few minutes.', es: 'Probá de nuevo en unos minutos.' },
  insecureConnection: { en: 'This connection is not secure', es: 'Esta conexión no es segura' },
  connectionUnsafe: { en: 'Horizon could not establish a secure connection to this site.', es: 'Horizon no pudo establecer una conexión segura con este sitio.' },
  blockedAddress: { en: 'This address is blocked', es: 'Esta dirección está bloqueada' },
  addressBlocked: { en: 'Horizon cannot open this address.', es: 'Horizon no puede abrir esta dirección.' },
  pageCrashed: { en: 'This page crashed', es: 'Esta página dejó de funcionar' },
  reloadPage: { en: 'Reload the page to continue.', es: 'Recargá la página para seguir.' },
  tryLoadingAgain: { en: 'Try loading the page again.', es: 'Probá cargar la página de nuevo.' },
  retry: { en: 'Try again', es: 'Volver a intentar' },
  removeBookmark: { en: 'Remove bookmark', es: 'Quitar favorito' },
  zoomReset: { en: 'Reset page zoom', es: 'Restablecer zoom de la página' },
  theme: { en: 'Theme', es: 'Tema' },
  amber: { en: 'Amber', es: 'Amber' },
  daylight: { en: 'Daylight', es: 'Daylight' },
} as const;

export type CopyKey = keyof typeof copy;
export const text = (key: CopyKey, language: Language): string => copy[key][language];
